# permissions for end users to edit ordereddeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ordereddeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-sequential-operator
    app.kubernetes.io/part-of: k8s-sequential-operator
    app.kubernetes.io/managed-by: kustomize
  name: ordereddeployment-editor-role
rules:
- apiGroups:
  - app.zhtang.github.io
  resources:
  - ordereddeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.zhtang.github.io
  resources:
  - ordereddeployments/status
  verbs:
  - get
